name: konrad
channels:
    - conda-forge
    - rttools
dependencies:
    - python==3.10
    - jupyter-book
    - matplotlib>=2.0.0
    - netcdf4>=1.2.7
    - numpy>1.22.0
    - pyarts>=2.5.8
    - pytest
    - scipy>=0.19.0
    - sphinx
    - sphinx_rtd_theme
    - typhon>=0.7.0
    - xarray>=0.9.1
    - pip<25.3  # pip 25.3 enforces changes to the build system
    - pip:
        - climt
        - sympl>=0.4.0
