name: konrad-dev
dependencies:
    - python>=3.6
    - matplotlib>=2.0.0
    - netcdf4>=1.2.7
    - numpy>=1.16.1
    - scipy>=0.19.0
    - typhon>=0.7.0
    - xarray>=0.9.1
    - sphinx
    - sphinx_rtd_theme
    - pytest
    - pip
    - pip:
        - climt==0.16.9
        - pyarts
        - sympl>=0.4.0
channels:
    - defaults
    - rttools
